[package]
name = 'inchat'
version = '1.0.0'

[dependencies.AptosProfileSystem]
git = 'https://github.com/JustaLiang/aptos-profile-system.git'
rev = 'main'
subdir = '.'

[addresses]
injoy_labs = "0x6064192b201dc3a7cff0513654610b141e754c9eb1ff22d40622f858c9d912e9"
